
spring:
  # Spring JDBC Properties
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=donation
    username: postgres
    password: postgres
  # Flyway config
  flyway:
#    enabled: false
    schemas: donation
    outOfOrder: true
    baseline-version: 0
    baselineOnMigrate: true
    table: schema_history
#  jpa:
#    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile

cloudinary:
  cloud_name:
  api_key:
  api_secret:
  secure: true
  folder: donation/file/
  path: https://res.cloudinary.com/dln5uctjy/

sender:
  mail:
    active: true
    host: smtp.gmail.com
    port: 587
    username:
    password:
    from: DONATION APP LOCAL <email.local.notification@gmail.com>

paypal:
  client-id:
  client-secret:
  payment-api: https://sandbox.paypal.com/v2/payments/captures/